Namespace Utilities
    'This code was auto generated by a tool
    ''' <summary>
    ''' A helper class to locate resources
    ''' </summary>
    Public Class ResourceResolver
#Region "Methods"
        Public Shared Function GetResource(key As String) As Object
            Return Application.Current.Resources(key)
        End Function
        Public Shared Sub SetResource(key As String, value As Object)
            Application.Current.Resources(key) = value
        End Sub
#End Region
        Public Class Strings
            Public Shared Property ABOUT As System.String
                Get
                    Return Application.Current.Resources("LOC_ABOUT")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_ABOUT") = value
                End Set
            End Property
            Public Shared Property QUERY_APP_RESTART As System.String
                Get
                    Return Application.Current.Resources("LOC_QUERY_APP_RESTART")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_QUERY_APP_RESTART") = value
                End Set
            End Property
            Public Shared Property QUERY_UPDATES_ERROR As System.String
                Get
                    Return Application.Current.Resources("LOC_QUERY_UPDATES_ERROR")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_QUERY_UPDATES_ERROR") = value
                End Set
            End Property
            Public Shared Property LOC_QUERY_UPDATES_NOTFOUND As System.String
                Get
                    Return Application.Current.Resources("LOC_LOC_QUERY_UPDATES_NOTFOUND")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_LOC_QUERY_UPDATES_NOTFOUND") = value
                End Set
            End Property
            Public Shared Property QUERY_UPDATES_FOUND As System.String
                Get
                    Return Application.Current.Resources("LOC_QUERY_UPDATES_FOUND")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_QUERY_UPDATES_FOUND") = value
                End Set
            End Property
            Public Shared Property ADD As System.String
                Get
                    Return Application.Current.Resources("LOC_ADD")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_ADD") = value
                End Set
            End Property
            Public Shared Property ADDTOPLAYLIST As System.String
                Get
                    Return Application.Current.Resources("LOC_ADDTOPLAYLIST")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_ADDTOPLAYLIST") = value
                End Set
            End Property
            Public Shared Property ALBUM As System.String
                Get
                    Return Application.Current.Resources("LOC_ALBUM")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_ALBUM") = value
                End Set
            End Property
            Public Shared Property APPEND As System.String
                Get
                    Return Application.Current.Resources("LOC_APPEND")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_APPEND") = value
                End Set
            End Property
            Public Shared Property APPNAME As System.String
                Get
                    Return Application.Current.Resources("LOC_APPNAME")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_APPNAME") = value
                End Set
            End Property
            Public Shared Property ARTIST As System.String
                Get
                    Return Application.Current.Resources("LOC_ARTIST")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_ARTIST") = value
                End Set
            End Property
            Public Shared Property AUDIOEFFECTS As System.String
                Get
                    Return Application.Current.Resources("LOC_AUDIOEFFECTS")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_AUDIOEFFECTS") = value
                End Set
            End Property
            Public Shared Property AUTOPLAY As System.String
                Get
                    Return Application.Current.Resources("LOC_AUTOPLAY")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_AUTOPLAY") = value
                End Set
            End Property
            Public Shared Property BIND As System.String
                Get
                    Return Application.Current.Resources("LOC_BIND")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_BIND") = value
                End Set
            End Property
            Public Shared Property CLEAR As System.String
                Get
                    Return Application.Current.Resources("LOC_CLEAR")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_CLEAR") = value
                End Set
            End Property
            Public Shared Property CLOSE As System.String
                Get
                    Return Application.Current.Resources("LOC_CLOSE")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_CLOSE") = value
                End Set
            End Property
            Public Shared Property CLOSINGBEHAVIOUR As System.String
                Get
                    Return Application.Current.Resources("LOC_CLOSINGBEHAVIOUR")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_CLOSINGBEHAVIOUR") = value
                End Set
            End Property
            Public Shared Property [CONTINUE] As System.String
                Get
                    Return Application.Current.Resources("LOC_CONTINUE")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_CONTINUE") = value
                End Set
            End Property
            Public Shared Property COUNT As System.String
                Get
                    Return Application.Current.Resources("LOC_COUNT")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_COUNT") = value
                End Set
            End Property
            Public Shared Property CROSSFADE As System.String
                Get
                    Return Application.Current.Resources("LOC_CROSSFADE")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_CROSSFADE") = value
                End Set
            End Property
            Public Shared Property CUSTOM As System.String
                Get
                    Return Application.Current.Resources("LOC_CUSTOM")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_CUSTOM") = value
                End Set
            End Property
            Public Shared Property [DEFAULT] As System.String
                Get
                    Return Application.Current.Resources("LOC_DEFAULT")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_DEFAULT") = value
                End Set
            End Property
            Public Shared Property DEVELOPER As System.String
                Get
                    Return Application.Current.Resources("LOC_DEVELOPER")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_DEVELOPER") = value
                End Set
            End Property
            Public Shared Property DURATION As System.String
                Get
                    Return Application.Current.Resources("LOC_DURATION")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_DURATION") = value
                End Set
            End Property
            Public Shared Property EDIT As System.String
                Get
                    Return Application.Current.Resources("LOC_EDIT")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_EDIT") = value
                End Set
            End Property
            Public Shared Property ENQUEUE As System.String
                Get
                    Return Application.Current.Resources("LOC_ENQUEUE")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_ENQUEUE") = value
                End Set
            End Property
            Public Shared Property [EXIT] As System.String
                Get
                    Return Application.Current.Resources("LOC_EXIT")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_EXIT") = value
                End Set
            End Property
            Public Shared Property FADEAUDIO As System.String
                Get
                    Return Application.Current.Resources("LOC_FADEAUDIO")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_FADEAUDIO") = value
                End Set
            End Property
            Public Shared Property FAVORITES As System.String
                Get
                    Return Application.Current.Resources("LOC_FAVORITES")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_FAVORITES") = value
                End Set
            End Property
            Public Shared Property FILE As System.String
                Get
                    Return Application.Current.Resources("LOC_FILE")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_FILE") = value
                End Set
            End Property
            Public Shared Property FRAMERATE As System.String
                Get
                    Return Application.Current.Resources("LOC_FRAMERATE")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_FRAMERATE") = value
                End Set
            End Property
            Public Shared Property GENERAL As System.String
                Get
                    Return Application.Current.Resources("LOC_GENERAL")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_GENERAL") = value
                End Set
            End Property
            Public Shared Property HEIGHT As System.String
                Get
                    Return Application.Current.Resources("LOC_HEIGHT")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_HEIGHT") = value
                End Set
            End Property
            Public Shared Property HIDE As System.String
                Get
                    Return Application.Current.Resources("LOC_HIDE")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_HIDE") = value
                End Set
            End Property
            Public Shared Property HINT_KEYBOARD_NAVIGATION As System.String
                Get
                    Return Application.Current.Resources("LOC_HINT_KEYBOARD_NAVIGATION")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_HINT_KEYBOARD_NAVIGATION") = value
                End Set
            End Property
            Public Shared Property HOME As System.String
                Get
                    Return Application.Current.Resources("LOC_HOME")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_HOME") = value
                End Set
            End Property
            Public Shared Property HOTKEY As System.String
                Get
                    Return Application.Current.Resources("LOC_HOTKEY")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_HOTKEY") = value
                End Set
            End Property
            Public Shared Property HOTKEYS As System.String
                Get
                    Return Application.Current.Resources("LOC_HOTKEYS")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_HOTKEYS") = value
                End Set
            End Property
            Public Shared Property HOURS As System.String
                Get
                    Return Application.Current.Resources("LOC_HOURS")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_HOURS") = value
                End Set
            End Property
            Public Shared Property KEYBOARD As System.String
                Get
                    Return Application.Current.Resources("LOC_KEYBOARD")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_KEYBOARD") = value
                End Set
            End Property
            Public Shared Property LIBRARY As System.String
                Get
                    Return Application.Current.Resources("LOC_LIBRARY")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_LIBRARY") = value
                End Set
            End Property
            Public Shared Property MINIMIZE As System.String
                Get
                    Return Application.Current.Resources("LOC_MINIMIZE")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_MINIMIZE") = value
                End Set
            End Property
            Public Shared Property MINUTES As System.String
                Get
                    Return Application.Current.Resources("LOC_MINUTES")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_MINUTES") = value
                End Set
            End Property
            Public Shared Property MOSTPLAYED As System.String
                Get
                    Return Application.Current.Resources("LOC_MOSTPLAYED")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_MOSTPLAYED") = value
                End Set
            End Property
            Public Shared Property [NEW] As System.String
                Get
                    Return Application.Current.Resources("LOC_NEW")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_NEW") = value
                End Set
            End Property
            Public Shared Property NONE As System.String
                Get
                    Return Application.Current.Resources("LOC_NONE")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_NONE") = value
                End Set
            End Property
            Public Shared Property NORMAL As System.String
                Get
                    Return Application.Current.Resources("LOC_NORMAL")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_NORMAL") = value
                End Set
            End Property
            Public Shared Property NOTIFY As System.String
                Get
                    Return Application.Current.Resources("LOC_NOTIFY")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_NOTIFY") = value
                End Set
            End Property
            Public Shared Property NOWPLAYING As System.String
                Get
                    Return Application.Current.Resources("LOC_NOWPLAYING")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_NOWPLAYING") = value
                End Set
            End Property
            Public Shared Property OPEN As System.String
                Get
                    Return Application.Current.Resources("LOC_OPEN")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_OPEN") = value
                End Set
            End Property
            Public Shared Property OUTPUT As System.String
                Get
                    Return Application.Current.Resources("LOC_OUTPUT")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_OUTPUT") = value
                End Set
            End Property
            Public Shared Property PAUSE As System.String
                Get
                    Return Application.Current.Resources("LOC_PAUSE")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_PAUSE") = value
                End Set
            End Property
            Public Shared Property PLAY As System.String
                Get
                    Return Application.Current.Resources("LOC_PLAY")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_PLAY") = value
                End Set
            End Property
            Public Shared Property PLAYCOUNT As System.String
                Get
                    Return Application.Current.Resources("LOC_PLAYCOUNT")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_PLAYCOUNT") = value
                End Set
            End Property
            Public Shared Property PLAYER As System.String
                Get
                    Return Application.Current.Resources("LOC_PLAYER")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_PLAYER") = value
                End Set
            End Property
            Public Shared Property PLAYINGFROM As System.String
                Get
                    Return Application.Current.Resources("LOC_PLAYINGFROM")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_PLAYINGFROM") = value
                End Set
            End Property
            Public Shared Property PLAYLIST As System.String
                Get
                    Return Application.Current.Resources("LOC_PLAYLIST")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_PLAYLIST") = value
                End Set
            End Property
            Public Shared Property PREVIEW As System.String
                Get
                    Return Application.Current.Resources("LOC_PREVIEW")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_PREVIEW") = value
                End Set
            End Property
            Public Shared Property PROPERTIES As System.String
                Get
                    Return Application.Current.Resources("LOC_PROPERTIES")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_PROPERTIES") = value
                End Set
            End Property
            Public Shared Property QUERY As System.String
                Get
                    Return Application.Current.Resources("LOC_QUERY")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_QUERY") = value
                End Set
            End Property
            Public Shared Property QUERY_FORCESTOP As System.String
                Get
                    Return Application.Current.Resources("LOC_QUERY_FORCESTOP")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_QUERY_FORCESTOP") = value
                End Set
            End Property
            Public Shared Property QUERY_SETTINGSRESET As System.String
                Get
                    Return Application.Current.Resources("LOC_QUERY_SETTINGSRESET")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_QUERY_SETTINGSRESET") = value
                End Set
            End Property
            Public Shared Property QUERY_FILEUNLOCK As System.String
                Get
                    Return Application.Current.Resources("LOC_QUERY_FILEUNLOCK")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_QUERY_FILEUNLOCK") = value
                End Set
            End Property
            Public Shared Property QUERY_FILEACCESSDENIED As System.String
                Get
                    Return Application.Current.Resources("LOC_QUERY_FILEACCESSDENIED")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_QUERY_FILEACCESSDENIED") = value
                End Set
            End Property
            Public Shared Property QUERY_CONFIRM_MULTIPLE As System.String
                Get
                    Return Application.Current.Resources("LOC_QUERY_CONFIRM_MULTIPLE")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_QUERY_CONFIRM_MULTIPLE") = value
                End Set
            End Property
            Public Shared Property QUERY_SELECTFROMBELOW As System.String
                Get
                    Return Application.Current.Resources("LOC_QUERY_SELECTFROMBELOW")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_QUERY_SELECTFROMBELOW") = value
                End Set
            End Property
            Public Shared Property QUERY_TIMEREND As System.String
                Get
                    Return Application.Current.Resources("LOC_QUERY_TIMEREND")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_QUERY_TIMEREND") = value
                End Set
            End Property
            Public Shared Property QUERY_URL As System.String
                Get
                    Return Application.Current.Resources("LOC_QUERY_URL")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_QUERY_URL") = value
                End Set
            End Property
            Public Shared Property QUERY_FILELOCATION As System.String
                Get
                    Return Application.Current.Resources("LOC_QUERY_FILELOCATION")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_QUERY_FILELOCATION") = value
                End Set
            End Property
            Public Shared Property QUERY_FILEPLAY As System.String
                Get
                    Return Application.Current.Resources("LOC_QUERY_FILEPLAY")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_QUERY_FILEPLAY") = value
                End Set
            End Property
            Public Shared Property QUEUE As System.String
                Get
                    Return Application.Current.Resources("LOC_QUEUE")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_QUEUE") = value
                End Set
            End Property
            Public Shared Property REBUILD As System.String
                Get
                    Return Application.Current.Resources("LOC_REBUILD")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_REBUILD") = value
                End Set
            End Property
            Public Shared Property REFRESHCOVER As System.String
                Get
                    Return Application.Current.Resources("LOC_REFRESHCOVER")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_REFRESHCOVER") = value
                End Set
            End Property
            Public Shared Property REMOTETAGSREADING As System.String
                Get
                    Return Application.Current.Resources("LOC_REMOTETAGSREADING")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_REMOTETAGSREADING") = value
                End Set
            End Property
            Public Shared Property REMOVE As System.String
                Get
                    Return Application.Current.Resources("LOC_REMOVE")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_REMOVE") = value
                End Set
            End Property
            Public Shared Property REMOVEFROM As System.String
                Get
                    Return Application.Current.Resources("LOC_REMOVEFROM")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_REMOVEFROM") = value
                End Set
            End Property
            Public Shared Property RESOLUTION As System.String
                Get
                    Return Application.Current.Resources("LOC_RESOLUTION")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_RESOLUTION") = value
                End Set
            End Property
            Public Shared Property [RETURN] As System.String
                Get
                    Return Application.Current.Resources("LOC_RETURN")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_RETURN") = value
                End Set
            End Property
            Public Shared Property SAVE As System.String
                Get
                    Return Application.Current.Resources("LOC_SAVE")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_SAVE") = value
                End Set
            End Property
            Public Shared Property SCAN As System.String
                Get
                    Return Application.Current.Resources("LOC_SCAN")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_SCAN") = value
                End Set
            End Property
            Public Shared Property SEARCH As System.String
                Get
                    Return Application.Current.Resources("LOC_SEARCH")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_SEARCH") = value
                End Set
            End Property
            Public Shared Property SECONDS As System.String
                Get
                    Return Application.Current.Resources("LOC_SECONDS")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_SECONDS") = value
                End Set
            End Property
            Public Shared Property SETTINGS As System.String
                Get
                    Return Application.Current.Resources("LOC_SETTINGS")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_SETTINGS") = value
                End Set
            End Property
            Public Shared Property SILENCESKIP As System.String
                Get
                    Return Application.Current.Resources("LOC_SILENCESKIP")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_SILENCESKIP") = value
                End Set
            End Property
            Public Shared Property SKIP As System.String
                Get
                    Return Application.Current.Resources("LOC_SKIP")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_SKIP") = value
                End Set
            End Property
            Public Shared Property SLEEPTIMER As System.String
                Get
                    Return Application.Current.Resources("LOC_SLEEPTIMER")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_SLEEPTIMER") = value
                End Set
            End Property
            Public Shared Property SONG As System.String
                Get
                    Return Application.Current.Resources("LOC_SONG")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_SONG") = value
                End Set
            End Property
            Public Shared Property SORT As System.String
                Get
                    Return Application.Current.Resources("LOC_SORT")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_SORT") = value
                End Set
            End Property
            Public Shared Property SOURCES As System.String
                Get
                    Return Application.Current.Resources("LOC_SOURCES")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_SOURCES") = value
                End Set
            End Property
            Public Shared Property STARTUPBEHAVIOUR As System.String
                Get
                    Return Application.Current.Resources("LOC_STARTUPBEHAVIOUR")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_STARTUPBEHAVIOUR") = value
                End Set
            End Property
            Public Shared Property STARTUPCHECK As System.String
                Get
                    Return Application.Current.Resources("LOC_STARTUPCHECK")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_STARTUPCHECK") = value
                End Set
            End Property
            Public Shared Property SYSTEMTRAY As System.String
                Get
                    Return Application.Current.Resources("LOC_SYSTEMTRAY")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_SYSTEMTRAY") = value
                End Set
            End Property
            Public Shared Property TABS As System.String
                Get
                    Return Application.Current.Resources("LOC_TABS")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_TABS") = value
                End Set
            End Property
            Public Shared Property TEXT_LIBRARY_SCAN_RESULT As System.String
                Get
                    Return Application.Current.Resources("LOC_TEXT_LIBRARY_SCAN_RESULT")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_TEXT_LIBRARY_SCAN_RESULT") = value
                End Set
            End Property
            Public Shared Property TEXT_LIBRARY_SCAN_RESULT_REMOVE_FAILURE As System.String
                Get
                    Return Application.Current.Resources("LOC_TEXT_LIBRARY_SCAN_RESULT_REMOVE_FAILURE")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_TEXT_LIBRARY_SCAN_RESULT_REMOVE_FAILURE") = value
                End Set
            End Property
            Public Shared Property TITLE As System.String
                Get
                    Return Application.Current.Resources("LOC_TITLE")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_TITLE") = value
                End Set
            End Property
            Public Shared Property TOTALFAVORITETRACKS As System.String
                Get
                    Return Application.Current.Resources("LOC_TOTALFAVORITETRACKS")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_TOTALFAVORITETRACKS") = value
                End Set
            End Property
            Public Shared Property URL As System.String
                Get
                    Return Application.Current.Resources("LOC_URL")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_URL") = value
                End Set
            End Property
            Public Shared Property VIEW As System.String
                Get
                    Return Application.Current.Resources("LOC_VIEW")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_VIEW") = value
                End Set
            End Property
            Public Shared Property VISUALIZER As System.String
                Get
                    Return Application.Current.Resources("LOC_VISUALIZER")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_VISUALIZER") = value
                End Set
            End Property
            Public Shared Property WIDTH As System.String
                Get
                    Return Application.Current.Resources("LOC_WIDTH")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_WIDTH") = value
                End Set
            End Property
            Public Shared Property INDEX As System.String
                Get
                    Return Application.Current.Resources("LOC_INDEX")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_INDEX") = value
                End Set
            End Property
            Public Shared Property FROM As System.String
                Get
                    Return Application.Current.Resources("LOC_FROM")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_FROM") = value
                End Set
            End Property
            Public Shared Property [TO] As System.String
                Get
                    Return Application.Current.Resources("LOC_TO")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_TO") = value
                End Set
            End Property
            Public Shared Property GREETING_MORNING As System.String
                Get
                    Return Application.Current.Resources("LOC_GREETING_MORNING")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_GREETING_MORNING") = value
                End Set
            End Property
            Public Shared Property GREETING_AFTERNOON As System.String
                Get
                    Return Application.Current.Resources("LOC_GREETING_AFTERNOON")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_GREETING_AFTERNOON") = value
                End Set
            End Property
            Public Shared Property GREETING_EVENING As System.String
                Get
                    Return Application.Current.Resources("LOC_GREETING_EVENING")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_GREETING_EVENING") = value
                End Set
            End Property
            Public Shared Property GREETING_NIGHT As System.String
                Get
                    Return Application.Current.Resources("LOC_GREETING_NIGHT")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_GREETING_NIGHT") = value
                End Set
            End Property
            Public Shared Property QUERY_NOMATCHES As System.String
                Get
                    Return Application.Current.Resources("LOC_QUERY_NOMATCHES")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_QUERY_NOMATCHES") = value
                End Set
            End Property
            Public Shared Property QUERY_KEEPPICTURES As System.String
                Get
                    Return Application.Current.Resources("LOC_QUERY_KEEPPICTURES")
                End Get
                Set(value As System.String)
                    Application.Current.Resources("LOC_QUERY_KEEPPICTURES") = value
                End Set
            End Property
        End Class
        Public Class Numerics
        End Class
        Public Class Other
        End Class
        Public Class Images
            Public Shared Property SPEAKER As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_SPEAKER")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_SPEAKER") = value
                End Set
            End Property
            Public Shared Property RANDOM As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_RANDOM")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_RANDOM") = value
                End Set
            End Property
            Public Shared Property CLOCK As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_CLOCK")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_CLOCK") = value
                End Set
            End Property
            Public Shared Property ARROW_RIGHT As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_ARROW_RIGHT")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_ARROW_RIGHT") = value
                End Set
            End Property
            Public Shared Property BACKGROUND_LINES As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_BACKGROUND_LINES")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_BACKGROUND_LINES") = value
                End Set
            End Property
            Public Shared Property ARROW_LEFT As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_ARROW_LEFT")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_ARROW_LEFT") = value
                End Set
            End Property
            Public Shared Property [LOOP] As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_LOOP")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_LOOP") = value
                End Set
            End Property
            Public Shared Property LOOP_ALL As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_LOOP_ALL")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_LOOP_ALL") = value
                End Set
            End Property
            Public Shared Property VOLUME As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_VOLUME")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_VOLUME") = value
                End Set
            End Property
            Public Shared Property CIRCLE_DELETE As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_CIRCLE_DELETE")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_CIRCLE_DELETE") = value
                End Set
            End Property
            Public Shared Property LOOP_ONE As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_LOOP_ONE")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_LOOP_ONE") = value
                End Set
            End Property
            Public Shared Property HEARTS As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_HEARTS")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_HEARTS") = value
                End Set
            End Property
            Public Shared Property CIRCLE_ARROW As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_CIRCLE_ARROW")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_CIRCLE_ARROW") = value
                End Set
            End Property
            Public Shared Property [NEXT] As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_NEXT")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_NEXT") = value
                End Set
            End Property
            Public Shared Property STAR_FILLED As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_STAR_FILLED")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_STAR_FILLED") = value
                End Set
            End Property
            Public Shared Property APPICON As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_APPICON")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_APPICON") = value
                End Set
            End Property
            Public Shared Property STAR_EMPTY As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_STAR_EMPTY")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_STAR_EMPTY") = value
                End Set
            End Property
            Public Shared Property BACKGROUND_GEARS As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_BACKGROUND_GEARS")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_BACKGROUND_GEARS") = value
                End Set
            End Property
            Public Shared Property PLAYPAUSE As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_PLAYPAUSE")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_PLAYPAUSE") = value
                End Set
            End Property
            Public Shared Property CIRCLE_INFO As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_CIRCLE_INFO")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_CIRCLE_INFO") = value
                End Set
            End Property
            Public Shared Property [RETURN] As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_RETURN")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_RETURN") = value
                End Set
            End Property
            Public Shared Property PREVIOUS As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_PREVIOUS")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_PREVIOUS") = value
                End Set
            End Property
            Public Shared Property CIRCLE_ONE As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_CIRCLE_ONE")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_CIRCLE_ONE") = value
                End Set
            End Property
            Public Shared Property CIRCLE_ALL As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_CIRCLE_ALL")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_CIRCLE_ALL") = value
                End Set
            End Property
            Public Shared Property CIRCLE_SHUFFLE As System.Windows.Media.StreamGeometry
                Get
                    Return Application.Current.Resources("GEO_CIRCLE_SHUFFLE")
                End Get
                Set(value As System.Windows.Media.StreamGeometry)
                    Application.Current.Resources("GEO_CIRCLE_SHUFFLE") = value
                End Set
            End Property
        End Class
    End Class

End Namespace