'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class MySettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
    
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property APP_HOTKEYS() As String
        Get
            Return CType(Me("APP_HOTKEYS"),String)
        End Get
        Set
            Me("APP_HOTKEYS") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property APP_PLAYER_PLAYLIST() As String
        Get
            Return CType(Me("APP_PLAYER_PLAYLIST"),String)
        End Get
        Set
            Me("APP_PLAYER_PLAYLIST") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property APP_PLAYER_SETTINGS() As String
        Get
            Return CType(Me("APP_PLAYER_SETTINGS"),String)
        End Get
        Set
            Me("APP_PLAYER_SETTINGS") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
        "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
    Public Property APP_LIBRARY() As Global.System.Collections.Specialized.StringCollection
        Get
            Return CType(Me("APP_LIBRARY"),Global.System.Collections.Specialized.StringCollection)
        End Get
        Set
            Me("APP_LIBRARY") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
        "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
    Public Property APP_LIBRARY_PATHS() As Global.System.Collections.Specialized.StringCollection
        Get
            Return CType(Me("APP_LIBRARY_PATHS"),Global.System.Collections.Specialized.StringCollection)
        End Get
        Set
            Me("APP_LIBRARY_PATHS") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
        "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
    Public Property APP_PLAYER_PLAYLIST_CUSTOM() As Global.System.Collections.Specialized.StringCollection
        Get
            Return CType(Me("APP_PLAYER_PLAYLIST_CUSTOM"),Global.System.Collections.Specialized.StringCollection)
        End Get
        Set
            Me("APP_PLAYER_PLAYLIST_CUSTOM") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property APP_CLOSINGBEHAVIOUR() As Integer
        Get
            Return CType(Me("APP_CLOSINGBEHAVIOUR"),Integer)
        End Get
        Set
            Me("APP_CLOSINGBEHAVIOUR") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property APP_STARTUPBEHAVIOUR() As Integer
        Get
            Return CType(Me("APP_STARTUPBEHAVIOUR"),Integer)
        End Get
        Set
            Me("APP_STARTUPBEHAVIOUR") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Visible")>  _
    Public Property APP_VIEW_SIDEBAR_RIGHT_VISIBILITY() As Global.System.Windows.Visibility
        Get
            Return CType(Me("APP_VIEW_SIDEBAR_RIGHT_VISIBILITY"),Global.System.Windows.Visibility)
        End Get
        Set
            Me("APP_VIEW_SIDEBAR_RIGHT_VISIBILITY") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property APP_YOUTUBEDL_PATH() As String
        Get
            Return CType(Me("APP_YOUTUBEDL_PATH"),String)
        End Get
        Set
            Me("APP_YOUTUBEDL_PATH") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
        "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
    Public Property APP_PLAYER_RECENT() As Global.System.Collections.Specialized.StringCollection
        Get
            Return CType(Me("APP_PLAYER_RECENT"),Global.System.Collections.Specialized.StringCollection)
        End Get
        Set
            Me("APP_PLAYER_RECENT") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
    Public Property APP_PLAYER_RECENT_LIMIT() As Integer
        Get
            Return CType(Me("APP_PLAYER_RECENT_LIMIT"),Integer)
        End Get
        Set
            Me("APP_PLAYER_RECENT_LIMIT") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property APP_THEME_INDEX() As Integer
        Get
            Return CType(Me("APP_THEME_INDEX"),Integer)
        End Get
        Set
            Me("APP_THEME_INDEX") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property APP_VIEW_BIGCOVER() As Boolean
        Get
            Return CType(Me("APP_VIEW_BIGCOVER"),Boolean)
        End Get
        Set
            Me("APP_VIEW_BIGCOVER") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property APP_THEME_LIGHT() As Boolean
        Get
            Return CType(Me("APP_THEME_LIGHT"),Boolean)
        End Get
        Set
            Me("APP_THEME_LIGHT") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property APP_FIRSTRUN() As Boolean
        Get
            Return CType(Me("APP_FIRSTRUN"),Boolean)
        End Get
        Set
            Me("APP_FIRSTRUN") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.QuickBeat.MySettings
            Get
                Return Global.QuickBeat.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
